import "../../../../chunks/server.js";
//#region src/routes/debug/typography/+page.svelte
function _page($$renderer) {
	$$renderer.push(`<main class="mx-auto max-w-5xl px-6 py-12 space-y-16 svelte-b6w5fy"><header class="space-y-2 border-b-2 border-foreground pb-6 svelte-b6w5fy"><p class="text-xs uppercase tracking-[0.2em] text-muted-foreground svelte-b6w5fy">debug · typography</p> <h1 class="text-4xl font-black tracking-tight svelte-b6w5fy">Type sandbox</h1> <p class="text-sm text-muted-foreground max-w-xl svelte-b6w5fy">Three candidate font systems for body / UI / mono. Big display
      headings stay on the current Arial Black; these are alternatives for
      the surrounding text. Each system gets its own BARBRO logo to show
      personality.</p></header> <section class="space-y-6 svelte-b6w5fy"><div class="flex items-baseline justify-between gap-4 border-b border-foreground/20 pb-2 svelte-b6w5fy"><p class="text-[11px] uppercase tracking-[0.2em] text-muted-foreground svelte-b6w5fy">System 01</p> <p class="text-xs font-mono text-muted-foreground svelte-b6w5fy">Bricolage Grotesque · IBM Plex Mono</p></div> <div class="flex items-center justify-center py-10 svelte-b6w5fy"><div class="logo-brutal relative svelte-b6w5fy"><span class="logo-brutal-shadow svelte-b6w5fy" aria-hidden="true">BARBRO</span> <span class="logo-brutal-main svelte-b6w5fy">BARBRO</span> <span class="logo-brutal-stamp svelte-b6w5fy" aria-hidden="true">®</span></div></div> <div class="grid gap-6 md:grid-cols-2 font-brutal svelte-b6w5fy"><article class="space-y-3 svelte-b6w5fy"><h2 class="text-2xl font-bold tracking-tight svelte-b6w5fy">Bar-first songmaps for the live set</h2> <p class="text-base leading-relaxed text-foreground/80 svelte-b6w5fy">The grid editor lays out every beat, every section, every chord on the
          same canvas — what you hear in BarBro is exactly what plays in Ableton
          when you fire the scene.</p> <p class="text-sm text-foreground/60 svelte-b6w5fy">Smaller paragraph. Good for descriptions, helper text, settings panels.
          The wider Bricolage letterforms feel friendly without being cute.</p> <p class="font-mono text-xs text-muted-foreground svelte-b6w5fy">IBM Plex Mono · bar 41 · beat 3 · trim 1.245s</p></article> <article class="space-y-2 svelte-b6w5fy"><p class="text-[10px] uppercase tracking-widest text-muted-foreground svelte-b6w5fy">UI label</p> <p class="text-xs uppercase tracking-wider font-semibold svelte-b6w5fy">Drums · Bass · Guitar · Vocals · FX</p> <p class="text-sm svelte-b6w5fy">Body sample 14px — the workhorse weight.</p> <p class="text-base svelte-b6w5fy">Body sample 16px — comfortable read.</p> <p class="text-lg font-medium svelte-b6w5fy">Heading sample 18px medium.</p> <p class="text-xl font-semibold svelte-b6w5fy">Heading sample 20px semibold.</p></article></div></section> <section class="space-y-6 svelte-b6w5fy"><div class="flex items-baseline justify-between gap-4 border-b border-foreground/20 pb-2 svelte-b6w5fy"><p class="text-[11px] uppercase tracking-[0.2em] text-muted-foreground svelte-b6w5fy">System 02</p> <p class="text-xs font-mono text-muted-foreground svelte-b6w5fy">Inter · JetBrains Mono</p></div> <div class="flex items-center justify-center py-10 svelte-b6w5fy"><div class="logo-swiss svelte-b6w5fy"><span class="logo-swiss-letters svelte-b6w5fy">BARBRO</span> <span class="logo-swiss-marker svelte-b6w5fy" aria-hidden="true"></span></div></div> <div class="grid gap-6 md:grid-cols-2 font-swiss svelte-b6w5fy"><article class="space-y-3 svelte-b6w5fy"><h2 class="text-2xl font-semibold tracking-tight svelte-b6w5fy">Bar-first songmaps for the live set</h2> <p class="text-base leading-relaxed text-foreground/80 svelte-b6w5fy">The grid editor lays out every beat, every section, every chord on the
          same canvas — what you hear in BarBro is exactly what plays in Ableton
          when you fire the scene.</p> <p class="text-sm text-foreground/60 svelte-b6w5fy">Smaller paragraph. Good for descriptions, helper text, settings panels.
          Inter is the safest, most-tested UI font; subtle, gets out of the way.</p> <p class="font-mono text-xs text-muted-foreground tabular-nums svelte-b6w5fy">JetBrains Mono · bar 41 · beat 3 · trim 1.245s</p></article> <article class="space-y-2 svelte-b6w5fy"><p class="text-[10px] uppercase tracking-widest text-muted-foreground svelte-b6w5fy">UI label</p> <p class="text-xs uppercase tracking-wider font-semibold svelte-b6w5fy">Drums · Bass · Guitar · Vocals · FX</p> <p class="text-sm svelte-b6w5fy">Body sample 14px — the workhorse weight.</p> <p class="text-base svelte-b6w5fy">Body sample 16px — comfortable read.</p> <p class="text-lg font-medium svelte-b6w5fy">Heading sample 18px medium.</p> <p class="text-xl font-semibold svelte-b6w5fy">Heading sample 20px semibold.</p></article></div></section> <section class="space-y-6 svelte-b6w5fy"><div class="flex items-baseline justify-between gap-4 border-b border-foreground/20 pb-2 svelte-b6w5fy"><p class="text-[11px] uppercase tracking-[0.2em] text-muted-foreground svelte-b6w5fy">System 03</p> <p class="text-xs font-mono text-muted-foreground svelte-b6w5fy">Space Grotesk · Geist Mono</p></div> <div class="flex items-center justify-center py-10 svelte-b6w5fy"><div class="logo-geo svelte-b6w5fy"><span class="logo-geo-bar svelte-b6w5fy">BAR</span> <span class="logo-geo-bro svelte-b6w5fy">BRO</span></div></div> <div class="grid gap-6 md:grid-cols-2 font-geo svelte-b6w5fy"><article class="space-y-3 svelte-b6w5fy"><h2 class="text-2xl font-bold tracking-tight svelte-b6w5fy">Bar-first songmaps for the live set</h2> <p class="text-base leading-relaxed text-foreground/80 svelte-b6w5fy">The grid editor lays out every beat, every section, every chord on the
          same canvas — what you hear in BarBro is exactly what plays in Ableton
          when you fire the scene.</p> <p class="text-sm text-foreground/60 svelte-b6w5fy">Smaller paragraph. Good for descriptions, helper text, settings panels.
          Space Grotesk's geometric quirks give the chrome more character.</p> <p class="font-mono text-xs text-muted-foreground tabular-nums svelte-b6w5fy">Geist Mono · bar 41 · beat 3 · trim 1.245s</p></article> <article class="space-y-2 svelte-b6w5fy"><p class="text-[10px] uppercase tracking-widest text-muted-foreground svelte-b6w5fy">UI label</p> <p class="text-xs uppercase tracking-wider font-semibold svelte-b6w5fy">Drums · Bass · Guitar · Vocals · FX</p> <p class="text-sm svelte-b6w5fy">Body sample 14px — the workhorse weight.</p> <p class="text-base svelte-b6w5fy">Body sample 16px — comfortable read.</p> <p class="text-lg font-medium svelte-b6w5fy">Heading sample 18px medium.</p> <p class="text-xl font-semibold svelte-b6w5fy">Heading sample 20px semibold.</p></article></div></section> <section class="space-y-6 svelte-b6w5fy"><div class="flex items-baseline justify-between gap-4 border-b border-foreground/20 pb-2 svelte-b6w5fy"><p class="text-[11px] uppercase tracking-[0.2em] text-muted-foreground svelte-b6w5fy">System 04</p> <p class="text-xs font-mono text-muted-foreground svelte-b6w5fy">Archivo Black · DM Mono</p></div> <div class="flex items-center justify-center py-12 svelte-b6w5fy"><div class="logo-tabloid svelte-b6w5fy"><span class="logo-tabloid-back svelte-b6w5fy" aria-hidden="true">BARBRO</span> <span class="logo-tabloid-main svelte-b6w5fy">BARBRO</span> <span class="logo-tabloid-tag svelte-b6w5fy">EST. AGAIN</span></div></div> <div class="grid gap-6 md:grid-cols-2 font-tabloid svelte-b6w5fy"><article class="space-y-3 svelte-b6w5fy"><h2 class="text-2xl font-black uppercase italic tracking-tight svelte-b6w5fy">Bar-first songmaps for the live set.</h2> <p class="text-base leading-relaxed text-foreground/80 svelte-b6w5fy">The grid editor lays out every beat, every section, every chord on the
          same canvas — what you hear in BarBro is exactly what plays in Ableton
          when you fire the scene.</p> <p class="text-sm text-foreground/60 svelte-b6w5fy">Smaller paragraph. Body text in this system stays brutalist but
          readable. Archivo Black headlines hit hard.</p> <p class="font-mono text-xs text-muted-foreground tabular-nums svelte-b6w5fy">DM MONO · BAR 41 · BEAT 3 · TRIM 1.245s</p></article> <article class="space-y-2 svelte-b6w5fy"><p class="text-[10px] uppercase tracking-widest text-muted-foreground svelte-b6w5fy">UI label</p> <p class="text-xs uppercase tracking-wider font-bold svelte-b6w5fy">Drums · Bass · Guitar · Vocals · FX</p> <p class="text-sm svelte-b6w5fy">Body sample 14px — the workhorse weight.</p> <p class="text-base svelte-b6w5fy">Body sample 16px — comfortable read.</p> <p class="text-lg font-bold italic svelte-b6w5fy">HEADING SAMPLE 18PX BOLD ITALIC.</p> <p class="text-xl font-bold uppercase svelte-b6w5fy">Heading sample 20px uppercase.</p></article></div></section> <section class="space-y-6 svelte-b6w5fy"><div class="flex items-baseline justify-between gap-4 border-b border-foreground/20 pb-2 svelte-b6w5fy"><p class="text-[11px] uppercase tracking-[0.2em] text-muted-foreground svelte-b6w5fy">System 05</p> <p class="text-xs font-mono text-muted-foreground svelte-b6w5fy">Big Shoulders Display · Spline Sans Mono</p></div> <div class="flex items-center justify-center py-12 svelte-b6w5fy"><div class="logo-concrete svelte-b6w5fy"><div class="logo-concrete-bars svelte-b6w5fy" aria-hidden="true"></div> <span class="logo-concrete-text svelte-b6w5fy">BARBRO</span> <div class="logo-concrete-stripe svelte-b6w5fy" aria-hidden="true"><span class="svelte-b6w5fy">SETLIST</span><span class="svelte-b6w5fy">·</span><span class="svelte-b6w5fy">SYSTEM</span><span class="svelte-b6w5fy">·</span><span class="svelte-b6w5fy">VOL. 01</span></div></div></div> <div class="grid gap-6 md:grid-cols-2 font-concrete svelte-b6w5fy"><article class="space-y-3 svelte-b6w5fy"><h2 class="text-2xl font-black uppercase tracking-tight svelte-b6w5fy">Bar-first songmaps for the live set</h2> <p class="text-base leading-relaxed text-foreground/80 svelte-b6w5fy">The grid editor lays out every beat, every section, every chord on the
          same canvas — what you hear in BarBro is exactly what plays in Ableton
          when you fire the scene.</p> <p class="text-sm text-foreground/60 svelte-b6w5fy">Smaller paragraph. Big Shoulders condensed runs feel like signage —
          good for headers, labels, and any compact block that needs presence.</p> <p class="font-mono text-xs text-muted-foreground tabular-nums svelte-b6w5fy">Spline Sans Mono · bar 41 · beat 3 · trim 1.245s</p></article> <article class="space-y-2 svelte-b6w5fy"><p class="text-[10px] uppercase tracking-widest text-muted-foreground svelte-b6w5fy">UI label</p> <p class="text-xs uppercase tracking-wider font-black svelte-b6w5fy">Drums · Bass · Guitar · Vocals · FX</p> <p class="text-sm svelte-b6w5fy">Body sample 14px — the workhorse weight.</p> <p class="text-base svelte-b6w5fy">Body sample 16px — comfortable read.</p> <p class="text-lg font-bold uppercase svelte-b6w5fy">Heading sample 18px uppercase.</p> <p class="text-xl font-black uppercase svelte-b6w5fy">Heading sample 20px black.</p></article></div></section> <section class="space-y-6 svelte-b6w5fy"><div class="flex items-baseline justify-between gap-4 border-b border-foreground/20 pb-2 svelte-b6w5fy"><p class="text-[11px] uppercase tracking-[0.2em] text-muted-foreground svelte-b6w5fy">System 06</p> <p class="text-xs font-mono text-muted-foreground svelte-b6w5fy">Anton · Major Mono Display · VT323</p></div> <div class="flex items-center justify-center py-12 svelte-b6w5fy"><div class="logo-zine svelte-b6w5fy"><span class="logo-zine-r svelte-b6w5fy" aria-hidden="true">BARBRO</span> <span class="logo-zine-g svelte-b6w5fy" aria-hidden="true">BARBRO</span> <span class="logo-zine-b svelte-b6w5fy" aria-hidden="true">BARBRO</span> <span class="logo-zine-main svelte-b6w5fy">BARBRO</span> <span class="logo-zine-corner svelte-b6w5fy">→ ISSUE_07</span></div></div> <div class="grid gap-6 md:grid-cols-2 font-zine svelte-b6w5fy"><article class="space-y-3 svelte-b6w5fy"><h2 class="text-2xl font-normal uppercase tracking-tight svelte-b6w5fy">BAR-FIRST SONGMAPS FOR THE LIVE SET</h2> <p class="text-base leading-relaxed text-foreground/80 svelte-b6w5fy">The grid editor lays out every beat, every section, every chord on the
          same canvas — what you hear in BarBro is exactly what plays in Ableton
          when you fire the scene.</p> <p class="text-sm text-foreground/60 svelte-b6w5fy">Smaller paragraph. The Anton/Major Mono pairing reads like a
          photocopied zine masthead — heavy commitment to a vibe.</p> <p class="font-mono text-xs text-muted-foreground tabular-nums svelte-b6w5fy">VT323 · BAR 41 · BEAT 3 · TRIM 1.245s</p></article> <article class="space-y-2 svelte-b6w5fy"><p class="text-[10px] uppercase tracking-widest text-muted-foreground svelte-b6w5fy">UI label</p> <p class="text-xs uppercase tracking-wider font-normal svelte-b6w5fy">DRUMS · BASS · GUITAR · VOCALS · FX</p> <p class="text-sm svelte-b6w5fy">Body sample 14px — the workhorse weight.</p> <p class="text-base svelte-b6w5fy">Body sample 16px — comfortable read.</p> <p class="text-lg uppercase svelte-b6w5fy">HEADING SAMPLE 18PX.</p> <p class="text-xl uppercase svelte-b6w5fy">HEADING SAMPLE 20PX.</p></article></div></section> <footer class="border-t-2 border-foreground pt-6 svelte-b6w5fy"><p class="text-xs text-muted-foreground svelte-b6w5fy">Pick one → ship by overwriting <code class="font-mono bg-muted px-1 svelte-b6w5fy">--font-sans</code> / <code class="font-mono bg-muted px-1 svelte-b6w5fy">--font-mono</code> in <code class="font-mono bg-muted px-1 svelte-b6w5fy">src/app.css</code>.</p></footer></main>`);
	/**
	* Typography exploration sandbox.
	*
	* Three candidate font systems with a unique BARBRO logo treatment for
	* each. Display headings (the big "Edit" / "Welcome"-style) stay on the
	* existing Arial Black `--font-sans` — these systems are about everything
	* else (body, UI, mono, captions).
	*
	* The winner ships by overwriting `--font-sans` (or adding paired
	* `--font-display` + `--font-body`) in `src/app.css`.
	*/
}
//#endregion
export { _page as default };
