/**
 * The drum bus as LIVE Web Audio nodes.
 *
 * `drumBus.ts` is the offline version: pure DSP over Float32Arrays. A MIDI drum
 * track can't use it, but it must sound the same, so each stage is reproduced
 * here with the strongest available guarantee rather than a lookalike:
 *
 *   reverb      → ConvolverNode whose IR is GENERATED BY the pure `reverbWet`
 *   compression → AudioWorklet, a verbatim port of `applyBusCompression`
 *   saturation  → WaveShaper whose curve is SAMPLED FROM `applySaturation`
 *   normalize   → a static gain (the offline stage needs the whole buffer)
 *
 * The reverb deserves a note. `reverbWet` is linear and time-invariant — fixed
 * coefficients, no randomness — so its impulse response characterises it
 * COMPLETELY. Convolving with that IR is not an approximation of the reverb;
 * it is the reverb, computed a different way. And because the IR is produced by
 * the same function the renderer uses, the two cannot drift.
 *
 *   input ─┬──────────────────────────────────────────┐  dry, unity
 *          └─ wet(0.16) → split ─ L → convL ─ merge ──┤
 *                               └ R → convR ─┘        ▼
 *                    compressor → preGain(1/K) → shaper → normalize → tailKill → out
 */
import { REVERB_WET, applySaturation, reverbWet } from './drumBus'
import type { MixerInsert } from './mixerEngine'

/** RT60 is 0.9 s; 2 s of tail is ~-130 dB, and keeps the convolution cheap. */
const IR_SECONDS = 2
/** The right channel is skewed for decorrelation — same value `applyReverb` uses. */
const R_CHANNEL_SKEW_MS = 0.9

/**
 * `WaveShaperNode` clamps its input index to [-1, 1], so anything hotter is
 * hard-clipped at the curve's end. This bus runs BEFORE normalization and its
 * peaks genuinely exceed 1.0 (voices are peak-normalized to ~1 and reverb adds
 * on top), so the signal is scaled down by K into the curve, and the curve is
 * built to expect that — `curve[x] = saturate(K·x)`. Net effect: correct
 * saturation for |input| ≤ K instead of a hidden clipper at 1.0.
 */
const SHAPER_HEADROOM = 4
const SHAPER_POINTS = 8192

/** Where the worklet processor is served from (`static/` maps to the root). */
export const DRUM_COMPRESSOR_WORKLET_URL = '/worklets/drumBusCompressor.js'

export type DrumBusLive = MixerInsert & {
  /** The offline chain ends in an RMS normalize; live it is one gain. */
  setNormalizeGain: (g: number) => void
  /**
   * Duck the reverb tail on stop/seek. Without this the convolver rings for
   * ~0.9 s after the last hit, where the old WAV lane went silent instantly.
   * Stays ducked until `openTail()` — the scheduler reopens it when the part
   * starts again.
   */
  killTail: () => void
  /** Undo `killTail`. Called at the top of every schedule. */
  openTail: () => void
  /** False when the compressor worklet could not load (stage bypassed). */
  readonly compressed: boolean
}

const irCache = new Map<number, { l: Float32Array; r: Float32Array }>()
const moduleLoaded = new WeakMap<BaseAudioContext, Promise<boolean>>()

/**
 * The impulse response OF the pure reverb, per channel.
 *
 * Generated at the CONTEXT's sample rate, not the kit's: `reverbWet` derives
 * its comb/allpass delays from the rate it's given, so building at 48 kHz
 * yields the correct coefficients there and avoids the browser resampling the
 * IR (which would blur the pre-delay and comb spacing).
 *
 * This is the raw WET path, unscaled — the 0.16 send level is a gain node, so
 * the dry path stays at unity exactly as `applyReverb` leaves it.
 */
export function drumReverbIR(sampleRate: number): { l: Float32Array; r: Float32Array } {
  const cached = irCache.get(sampleRate)
  if (cached) return cached
  const n = Math.max(1, Math.floor(IR_SECONDS * sampleRate))
  const impulse = new Float32Array(n)
  impulse[0] = 1
  const ir = {
    l: reverbWet(impulse, sampleRate, 0),
    r: reverbWet(impulse, sampleRate, R_CHANNEL_SKEW_MS),
  }
  irCache.set(sampleRate, ir)
  return ir
}

/**
 * The saturation curve, SAMPLED FROM `applySaturation` rather than restating
 * `tanh(x·d)/tanh(d)` — one definition, so a change there can't desync this.
 * The domain is pre-scaled by `SHAPER_HEADROOM` (see above).
 */
export function buildSaturationCurve(): Float32Array<ArrayBuffer> {
  const curve = new Float32Array(new ArrayBuffer(SHAPER_POINTS * Float32Array.BYTES_PER_ELEMENT))
  const probe = new Float32Array(SHAPER_POINTS)
  for (let i = 0; i < SHAPER_POINTS; i++) {
    probe[i] = ((i / (SHAPER_POINTS - 1)) * 2 - 1) * SHAPER_HEADROOM
  }
  applySaturation(probe) // default drive — the same one the renderer uses
  curve.set(probe)
  return curve
}

async function ensureCompressorModule(ctx: BaseAudioContext): Promise<boolean> {
  const existing = moduleLoaded.get(ctx)
  if (existing) return existing
  const p = (async () => {
    const worklet = (ctx as AudioContext).audioWorklet
    if (!worklet) return false
    try {
      await worklet.addModule(DRUM_COMPRESSOR_WORKLET_URL)
      return true
    } catch (e) {
      console.warn('drum bus compressor worklet unavailable; stage bypassed', e)
      return false
    }
  })()
  moduleLoaded.set(ctx, p)
  return p
}

/**
 * Build the bus. Async only because the worklet module has to load.
 *
 * If the worklet can't load, compression is BYPASSED rather than replaced with
 * `DynamicsCompressorNode`. That node applies ~6 ms of internal lookahead,
 * which would put the whole drum lane late against the sample-aligned click —
 * a worse and much more noticeable error than missing glue compression.
 */
export async function createDrumBusLive(ctx: BaseAudioContext): Promise<DrumBusLive> {
  const input = ctx.createGain()
  const merge = ctx.createGain()

  // Dry stays at unity — `applyReverb` ADDS a send on top, it doesn't crossfade.
  input.connect(merge)

  // Two MONO convolvers rather than one stereo-IR convolver: the spec's
  // stereo-response matrixing is a corner I'd rather not bet the sound on, and
  // per-channel convolution is exactly what `applyReverb` does (L from L, R
  // from R, with the right channel skewed).
  const ir = drumReverbIR(ctx.sampleRate)
  const wet = ctx.createGain()
  wet.gain.value = REVERB_WET
  const splitter = ctx.createChannelSplitter(2)
  const merger = ctx.createChannelMerger(2)
  input.connect(wet)
  wet.connect(splitter)
  for (const [ch, data] of [ir.l, ir.r].entries()) {
    const buf = ctx.createBuffer(1, data.length, ctx.sampleRate)
    const copy = new Float32Array(new ArrayBuffer(data.length * Float32Array.BYTES_PER_ELEMENT))
    copy.set(data)
    buf.copyToChannel(copy, 0)
    const conv = ctx.createConvolver()
    // MUST be set before `.buffer`: the default `true` applies a spec
    // calibration scale that silently shifts the wet level by several dB.
    conv.normalize = false
    conv.buffer = buf
    splitter.connect(conv, ch)
    conv.connect(merger, 0, ch)
  }
  merger.connect(merge)

  const preGain = ctx.createGain()
  preGain.gain.value = 1 / SHAPER_HEADROOM
  const shaper = ctx.createWaveShaper()
  shaper.curve = buildSaturationCurve()
  // 'none' on purpose: the renderer applies tanh per sample with no
  // oversampling, and matching it matters more than the aliasing it avoids.
  shaper.oversample = 'none'

  const normalize = ctx.createGain()
  const tailKill = ctx.createGain()

  let compressed = false
  if (await ensureCompressorModule(ctx)) {
    try {
      const comp = new AudioWorkletNode(ctx as AudioContext, 'drum-bus-compressor', {
        numberOfInputs: 1,
        numberOfOutputs: 1,
        outputChannelCount: [2],
      })
      merge.connect(comp)
      comp.connect(preGain)
      compressed = true
    } catch (e) {
      console.warn('drum bus compressor node failed; stage bypassed', e)
    }
  }
  if (!compressed) merge.connect(preGain)

  preGain.connect(shaper)
  shaper.connect(normalize)
  normalize.connect(tailKill)

  return {
    input,
    output: tailKill,
    setNormalizeGain(g: number) {
      normalize.gain.value = Math.max(0, g)
    },
    killTail() {
      // A hard zero clicks; 6 ms is inaudible but long enough to be clean.
      // It STAYS closed — restoring it here would let the tail ring straight
      // back in, which is the bug this exists to prevent.
      const now = ctx.currentTime
      const g = tailKill.gain
      try {
        g.cancelScheduledValues(now)
        g.setValueAtTime(g.value, now)
        g.linearRampToValueAtTime(0, now + 0.006)
      } catch {
        /* context closed */
      }
    },
    openTail() {
      const now = ctx.currentTime
      const g = tailKill.gain
      try {
        g.cancelScheduledValues(now)
        g.setValueAtTime(g.value, now)
        g.linearRampToValueAtTime(1, now + 0.006)
      } catch {
        /* context closed */
      }
    },
    get compressed() {
      return compressed
    },
  }
}
